### ISSUE TITLE
fix export to recognize /

### ISSUE THREAD

**Issue by Thais-Malheiros** [biralavor/42_minishell#501]
## Command:
`export PATH=/nfs/homes/tmalheir/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

**Comment by Thais-Malheiros** [comment]
export PATH=/nfs/homes/tmalheir/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by biralavor** [comment]
I exported for a `z` variable , and I think it is working, isn't it?:
![image](https://github.com/user-attachments/assets/5a0d1463-b221-47e1-b37e-328360d4792a)
